spring.application.name=clearflow-settlement

# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=CLEARFLOW
spring.datasource.password=ClearFlow2026!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.flyway.user=CLEARFLOW
spring.flyway.password=ClearFlow2026!