spring.application.name=clearflow-settlement

# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=CLEARFLOW
spring.datasource.password=ClearFlow2026!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.flyway.user=CLEARFLOW
spring.flyway.password=ClearFlow2026!

# ==========================
# OBSERVABILITY / TRACING
# ==========================

management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# Actuator
management.endpoints.web.exposure.include=health,info,loggers,logfile

# Logging
logging.pattern.correlation=[${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]
logging.include-application-name=false
logging.file.name=logs/clearflow-settlement.log

# currency API
clearflow.integrations.currency-api.base-url=https://api.currencyapi.com/v3
clearflow.integrations.currency-api.api-key=API_KEY
